default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: travel_shiori_development

test:
  <<: *default
  database: travel_shiori_test

production:
  <<: *default
  # Render等のプラットフォームで提供されるDATABASE_URL環境変数を使用
  url: <%= ENV['DATABASE_URL'] %> 
  
  # 環境変数が利用できない場合のフォールバック（ユーザー名、ホスト、ポートなどをENVで管理）
  database: travel_shiori_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>